add: new field to getRoomData and update: getToken
myonaingwinn/laravel-twilio pull request #26
Opened 2022-06-14 06:32 UTC by HlainePoeEi

### What You did

-   [x] add new field in getRoomData function
-   [x] update getToken function

2022-06-14 06:38 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +                "type" => $request->type,
```suggestion
                "type" => $request->type?: 'group',
```

2022-06-14 06:52 UTC, myonaingwinn reviewed
Onegai

2022-06-14 06:53 UTC, myonaingwinn approved these changes

2022-06-14 06:56 UTC, myonaingwinn submitted a review, later dismissed
OK

2022-06-14 06:56 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +                "maxParticipantDuration" => 60000,
```suggestion
                "maxParticipantDuration" => 60000?:'',
```

2022-06-15 02:59 UTC, myonaingwinn requested changes

2022-06-15 02:59 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/CustomObject/RoomData.php
>      public function getRoomData($twilio)
Please move this File to **Model** directory.

2022-06-15 02:59 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/CustomObject/RoomData.php
>          $result = (array('Room List' => $rooms));
```suggestion
        $roomList = $rooms;
```

2022-06-15 02:59 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
>              $this->sid,
```suggestion
            $this->sid,
            $this->apiKey,
            $this->apiSecret,
            3600,
            $identity
        );
        $grant = new VideoGrant();
        $grant->setRoom($request->room);
        $token->addGrant($grant);
        return ['token' => $token->toJWT()];
    }
    public function getRoomList()
    {
        $twilio = new Client($this->sid, $this->authToken);
        $obj = new RoomData();
        $roomList = $obj->getRoomData($twilio);
        return response()->json(["roomList" => $roomList], 200);
}
```

2022-06-15 03:26 UTC, myonaingwinn requested changes

2022-06-15 03:26 UTC, myonaingwinn commented on app/Models/Room/RoomList.php
>      public function getRoomData($twilio)
```suggestion
    public function getRoomList($twilio)
```

2022-06-15 03:26 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +        $roomList = $obj->getRoomData($twilio);
```suggestion
        $roomList = $obj->getRoomList($twilio);
```

2022-06-15 03:27 UTC, myonaingwinn commented
@HlainePoeEi お疲れ様！
Let's add pagination count!

2022-06-15 03:36 UTC, HlainePoeEi commented on app/Http/Controllers/api/v1/RoomController.php
> +        $roomList = $obj->getRoomData($twilio);
controller htal ka getRoomList so tae function name chin same phit twar mhr moz e'dr ko update ma lote tot tar

2022-06-15 03:55 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +        $roomList = $obj->getRoomData($twilio);
分かりました。有難うございます。

2022-06-15 04:00 UTC, myonaingwinn requested changes

2022-06-15 04:00 UTC, myonaingwinn commented on app/Models/Room/RoomList.php
>          return $result;
```suggestion
        return $rooms;
```

2022-06-15 04:05 UTC, myonaingwinn requested changes

2022-06-15 04:05 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +                "MaxParticipants" => (empty($request->participant_number)) ? '50' : $request->participant_number,
```suggestion
                "MaxParticipants" => (empty($request->maxParticipants)) ? '50' : $request->maxParticipants,
```

2022-06-15 04:05 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +                "emptyRoomTimeout" => (empty($request->empty_room_timeout)) ? '1' : $request->empty_room_timeout,
```suggestion
                "emptyRoomTimeout" => (empty($request->emptyRoomTimeout)) ? '1' : $request->emptyRoomTimeout,
```

2022-06-15 04:05 UTC, myonaingwinn commented on app/Http/Controllers/api/v1/RoomController.php
> +                "type" => (empty($request->type)) ? 'group' : $request->type,
```suggestion
                "type" => (empty($request->roomType)) ? 'group' : $request->roomType,
```

2022-06-15 06:47 UTC, myonaingwinn approved these changes

2022-06-15 06:54 UTC, myonaingwinn approved these changes

2022-06-15 06:55 UTC, myonaingwinn commented
Arigatouuuuuu

2022-06-15 06:55 UTC, merged